name: roqqu
description: "Coding Assessment"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  get: ^4.7.2
  http: ^1.5.0
  web_socket_channel: ^3.0.3
  flutter_animate: ^4.5.2
  sprung: ^3.0.1
  google_fonts: ^6.3.2
  intl: ^0.20.2
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/fonts/
     - assets/svg/
     - assets/images/



  fonts:
   - family: FormaDJR
     fonts:
       - asset: assets/fonts/FormaDJR-Light.ttf
         weight: 300
       - asset: assets/fonts/FormaDJR-LightItalic.ttf
         weight: 300
         style: italic
       - asset: assets/fonts/FormaDJR-Regular.ttf
         weight: 400
       - asset: assets/fonts/FormaDJR-Italic.ttf
         weight: 400
         style: italic
       - asset: assets/fonts/FormaDJR-Medium.ttf
         weight: 500
       - asset: assets/fonts/FormaDJR-MediumItalic.ttf
         weight: 500
         style: italic
       - asset: assets/fonts/FormaDJR-Bold.ttf
         weight: 700
       - asset: assets/fonts/FormaDJR-BoldItalic.ttf
         weight: 700
         style: italic
       - asset: assets/fonts/FormaDJR-Black.ttf
         weight: 900
       - asset: assets/fonts/FormaDJR-BlackItalic.ttf
         weight: 900
         style: italic