class TradingEntry {
  final String pair;
  final String leverage;
  final double roi;
  final String traderName;
  final String traderType;
  final double entryPrice;
  final double exitPrice;
  final double amount;
  final String entryTime;
  final String exitTime;
  final bool isOpen;

  TradingEntry({
    required this.pair,
    required this.leverage,
    required this.roi,
    required this.traderName,
    required this.traderType,
    required this.entryPrice,
    required this.exitPrice,
    required this.amount,
    required this.entryTime,
    required this.exitTime,
    this.isOpen = false,
  });
}

final List<TradingEntry> tradingHistory = [
  TradingEntry(
    pair: 'BTCUSDT',
    leverage: '10X',
    roi: 3.28,
    traderType: 'PRO trader',
    traderName: 'BTC Master',
    entryPrice: 1.9661,
    exitPrice: 1.9728,
    amount: 1009.772,
    entryTime: '01:22 PM',
    exitTime: '02:45 PM',
  ),
  TradingEntry(
    pair: 'ETHUSDT',
    leverage: '5X',
    roi: -1.12,
    traderType: 'PRO trader',
    traderName: 'Ether Whale',
    entryPrice: 1.5612,
    exitPrice: 1.5430,
    amount: 785.430,
    entryTime: '11:10 AM',
    exitTime: '12:25 PM',
  ),
  TradingEntry(
    pair: 'ADAUSDT',
    leverage: '8X',
    roi: 4.76,
    traderType: 'Steady trader',
    traderName: 'Cardano Pro',
    entryPrice: 0.4872,
    exitPrice: 0.5100,
    amount: 902.340,
    entryTime: '10:15 AM',
    isOpen: true,
    exitTime: '10:50 AM',
  ),
  TradingEntry(
    pair: 'DOGEUSDT',
    leverage: '12X',
    roi: 9.85,
    traderType: 'Aggressive trader',
    traderName: 'Doge Lord',
    entryPrice: 0.0721,
    exitPrice: 0.0792,
    amount: 500.000,
    entryTime: '09:30 AM',
    isOpen: true,
    exitTime: '11:00 AM',
  ),
  TradingEntry(
    pair: 'SOLUSDT',
    leverage: '7X',
    roi: -2.44,
    traderType: 'PRO trader',
    traderName: 'Sol Genius',
    entryPrice: 24.77,
    exitPrice: 24.18,
    amount: 1250.900,
    entryTime: '02:05 PM',
    exitTime: '03:10 PM',
    isOpen: true,
  ),
  TradingEntry(
    pair: 'BNBUSDT',
    leverage: '6X',
    roi: 1.73,
    traderType: 'PRO trader',
    traderName: 'Binance King',
    entryPrice: 229.80,
    exitPrice: 233.70,
    amount: 678.000,
    entryTime: '04:00 PM',
    exitTime: '04:45 PM',
  ),
  TradingEntry(
    pair: 'XRPUSDT',
    leverage: '4X',
    roi: -0.83,
    traderType: 'Safe trader',
    traderName: 'Ripple Rider',
    entryPrice: 0.5289,
    exitPrice: 0.5245,
    amount: 340.210,
    entryTime: '12:10 PM',
    exitTime: '12:40 PM',
  ),
  TradingEntry(
    pair: 'LTCUSDT',
    leverage: '9X',
    roi: 5.14,
    traderType: 'PRO trader',
    traderName: 'Litecoin Legend',
    entryPrice: 72.45,
    exitPrice: 76.13,
    amount: 920.300,
    entryTime: '08:30 AM',
    exitTime: '09:15 AM',
  ),
  TradingEntry(
    pair: 'DOTUSDT',
    leverage: '10X',
    roi: -3.52,
    traderType: 'PRO trader',
    traderName: 'Polka Pro',
    entryPrice: 4.89,
    exitPrice: 4.69,
    amount: 1100.000,
    entryTime: '03:25 PM',
    exitTime: '04:00 PM',
  ),
  TradingEntry(
    pair: 'AVAXUSDT',
    leverage: '7X',
    roi: 2.92,
    traderType: 'Steady trader',
    traderName: 'Avalanche Ace',
    entryPrice: 11.65,
    exitPrice: 11.99,
    amount: 845.110,
    entryTime: '07:30 PM',
    exitTime: '08:15 PM',
  ),
  TradingEntry(
    pair: 'MATICUSDT',
    leverage: '5X',
    roi: 0.74,
    traderType: 'PRO trader',
    traderName: 'Polygon Pilot',
    entryPrice: 0.7251,
    exitPrice: 0.7310,
    amount: 720.500,
    entryTime: '06:05 PM',
    exitTime: '06:45 PM',
  ),
  TradingEntry(
    pair: 'SHIBUSDT',
    leverage: '20X',
    roi: 14.62,
    traderType: 'Aggressive trader',
    traderName: 'Shiba Samurai',
    entryPrice: 0.00000792,
    exitPrice: 0.00000908,
    amount: 200.000,
    entryTime: '05:10 PM',
    exitTime: '05:35 PM',
  ),
];
